version: 2
jobs:
  github-apiv4:
    docker:
      - image: circleci/node:10.18.0-browsers
    environment:
      - COMMIT_AUTHOR_EMAIL: "daviddisu8@gmail.com"
      - COMMIT_AUTHOR: "Circle CI"
    working_directory: ~/github-apiv4

    steps:
      - checkout
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  build_all:
    jobs:
      - github-apiv4
